name: 'Example composite GitHub action'
description: "Generate a browser screenshot using puppeteer of any URL, including local files. Supports custom CSS overrides and Jquery style rewrites of content."
author: hello@cloudposse.com
branding:
  icon: 'camera'
  color: 'white'
inputs:
  url:
    description: 'URL of the HTML content to convert to an image. Use file:// for local files'
    required: true
  css:
    description: 'Custom CSS overrides'
    required: false
  customizations:
    description: 'String representation of a YAML or JSON map of CSS paths (key) and replacement (value)'
    required: false
  output:
    description: 'Output image file path'
    required: true
  outputType:
    description: 'Output image type'
    default: png
  omitBackground:
    description: 'Omit the browser default background. Enable to support transparency.'
    default: true
  canvasWidth:
    description: 'Canvas width in pixels'
    required: true
  canvasHeight:
    description: 'Canvas height in pixels'
    required: true
  imageQuality:
    description: 'Quality of the output image (1-100, applicable for JPEG)'
    required: false
  consoleOutputEnabled:
    descripion: 'Whether or not to output the browser console log'
    default: true
  deviceScaleFactor:
    description: 'Specifies the device scale factor (pixel ratio) for the web page rendering. It determines how many physical pixels are used to represent a single logical pixel. For example, a device scale factor of 2 means one logical pixel is represented by two physical pixels, commonly used for high-DPI (Retina) displays. A value of 1 uses standard pixel density. This factor affects the resolution and quality of the rendered page or screenshot.'
    default: '2'
    required: false
  fullPage:
    description: 'Screen capture the entire page by scrolling down'
    default: false
  waitForTimeout:
    description: 'Number of miliseconds to delay before taking screenshot'
    default: 500
outputs:
  screenshot_file:
    description: "Output result placeholder"
    value: "${{ steps.context.outputs.action-result }}"
runs:
  using: "composite"
  steps:
    - name: Run puppeteer to take screenshot
      id: puppeteer-run
      uses: tj-actions/docker-run@v2
      with:
        image: ghcr.io/puppeteer/puppeteer:21.3.8
        name: puppeteer-chrome
        options: '-i --init --cap-add=SYS_ADMIN -v ${{ github.workspace }}:${{ github.workspace }}'
        args: |
          bash -c 'cd ${{ github.workspace }} && mkdir node_modules && chmod 777 node_modules && npm install && node main.js'  

    - id: context
      shell: bash
      run: |
          echo "file=${{ inputs.output }}" >> $GITHUB_OUTPUT

