name: Build and Push Docker Image

on:
    push:
        branches:
        - main
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Build
      id: build
      uses: cloudposse/github-action-docker-build-push@main
      with:
        registry: ghcr.io
        organization: "${{ github.event.repository.owner.login }}"
        repository: "${{ github.event.repository.name }}"
        login: "${{ github.actor }}"
        password: "${{ secrets.GITHUB_TOKEN }}"
        platforms: linux/amd64,linux/arm64

    - name: Docker Pull
      run: |
          docker pull ${{ steps.build.outputs.image }}:${{ steps.build.outputs.tag}} 

    - name: Docker Image Summary
      run: |
        docker inspect ${{ steps.build.outputs.image }}:${{ steps.build.outputs.tag}} > image.json

    - name: Convert JSON to HTML Table
      uses: Teebra/JSON-to-HTML-table@v2.0.0
      with:
        json-file: ./image.json

    - name: Job Summary
      run: |
        echo "## Docker Image Summary" >> $GITHUB_STEP_SUMMARY
        cat output.html >> $GITHUB_STEP_SUMMARY
